"""Add language field to posts

Revision ID: c32d2d1c1ffb
Revises: 61d5d4f73c5c
Create Date: 2021-01-29 18:16:37.509216

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c32d2d1c1ffb'
down_revision = '61d5d4f73c5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('language', sa.String(length=5), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'language')
    # ### end Alembic commands ###
